# Generated by Django 6.0 on 2025-12-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=255)),
                ('packaging_tags', models.JSONField(default=list)),
                ('eco_score', models.IntegerField()),
                ('image', models.URLField(blank=True)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('recycled', 'Recycled'), ('reused', 'Reused'), ('donated', 'Donated'), ('discarded', 'Discarded')], max_length=20)),
                ('points_awarded', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='inventory.inventoryitem')),
            ],
        ),
    ]
