# Generated by Django 6.0 on 2025-12-27 12:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏅", max_length=10)),
            ],
            options={"ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="CommunityGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(default="general", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("invite_code", models.CharField(blank=True, max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="EcoShopRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("carbon_saving_kg_month", models.FloatField(default=0)),
                ("offer_text", models.CharField(blank=True, max_length=150)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="eco_shop_recommendations", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="HabitReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("scan", "Scan"), ("disposal", "Disposal"), ("expiry", "Expiry"), ("custom", "Custom")],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("cadence_days", models.PositiveIntegerField(default=1)),
                ("next_trigger_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["next_trigger_at"]},
        ),
        migrations.CreateModel(
            name="ScoreSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(choices=[("weekly", "Weekly"), ("monthly", "Monthly")], max_length=16)),
                ("scope", models.CharField(choices=[("global", "Global"), ("city", "City")], max_length=16)),
                ("score_value", models.IntegerField(default=0)),
                ("percentile", models.FloatField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("locked_until", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WasteReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("photo_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")], default="pending", max_length=20
                    ),
                ),
                ("points_awarded", models.IntegerField(default=0)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("points_reward", models.IntegerField(default=0)),
                ("carbon_focus", models.CharField(blank=True, max_length=120)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="engagement.communitygroup")),
            ],
            options={"ordering": ["starts_at"]},
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(choices=[("member", "Member"), ("admin", "Admin")], default="member", max_length=16),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="engagement.communitygroup")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-joined_at"], "unique_together": {("user", "group")}},
        ),
        migrations.CreateModel(
            name="BadgeAward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("metric_value", models.FloatField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engagement.badge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-awarded_at"], "unique_together": {("user", "badge")}},
        ),
        migrations.CreateModel(
            name="EventParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("going", "Going"), ("interested", "Interested"), ("attended", "Attended")], default="going", max_length=20
                    ),
                ),
                ("proof_url", models.URLField(blank=True)),
                ("points_awarded", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="engagement.communityevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("user", "event")}},
        ),
    ]
